/*
    #327 Labels is not rounded
    https://github.com/kerssdead/charts/issues/327
 */

import { test } from '@playwright/test'
import Utils from './utils/Utils'
import Settings from './utils/Settings'
import { ChartType } from '../src/static/Enums'
import Clip from './utils/Clip'

test('Gauge labels should be formatted', async ({ page, browserName }) => {
    await Utils.setup(page, browserName)

    await Settings.enableInitAnimation(false)
    await Settings.gaugeMax(99)
    await Settings.chartType(ChartType.Gauge)

    await Utils.checkScreenshot(
        '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAUACQDASIAAhEBAxEB/8QAGgABAAEFAAAAAAAAAAAAAAAAAAQDBQYHCP/EACYQAAICAQQCAgEFAAAAAAAAAAECAwQFAAYREhQhBxMiFTEyQVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A6R3VuGrtvGpbtx2J3mmStXrVkDSzyueFRASByfZ9kAAEkjjVLau5YNwpdQVLVC/Qm8e3SthRLC5UMOSrMpBVgQykgg/7yNWb5TqWXp4DJ1Kli4MPmIL80FdDJK0QV43KoPbECXtwPZ6+veoO0Lc0ec3LuKbF5WOnmsjVrU42qOJSixJH90kZAaNOxbksBwo5PGgnxfIuNky8dcUMkMbJeOMjyxjTxXtBiv1j8u/8wUDdepb1zpR+RcdbytaBKGSTG2rj4+tlnjQVp7ClgUX8u/sowDFQpI4B/bnBqWPyIxOO2T+k5JbdTc3nSW2rOK3iLda0JRNx0JKkIFB7dv60wlDIti9s7NfEZKK5iM/5dm09d1rePFPJMkqzcdW7goAoPbknkDg6Dd2mmmgaaaaBpppoGmmmg//Z',
        new Clip(67, 656, 36, 20)
    )
})