/*
    #327 Labels is not rounded
    https://github.com/kerssdead/charts/issues/327
 */

import { test } from '@playwright/test'
import Utils from './utils/Utils'
import Settings from './utils/Settings'
import { ChartType } from '../src/static/Enums'
import Clip from './utils/Clip'

test('Gauge labels should be formatted', async ({ page, browserName }) => {
    await Utils.setup(page, browserName)

    await Settings.enableInitAnimation(false)
    await Settings.gaugeMax(99)
    await Settings.chartType(ChartType.Gauge)

    await Utils.checkScreenshot(
        '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAUACQDASIAAhEBAxEB/8QAGgABAAEFAAAAAAAAAAAAAAAAAAQBBQYHCP/EACUQAAICAgIBBAIDAAAAAAAAAAECAwQABQYREgcTFCEiMRUyQf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDo/lfIqvG6ME9iCzanszrVq1aqhpbErAkIoJA/SsSSQAFJJynFeR1+RVrbR1rNK3TnNW3TtBRLBIAG6PiSpBVlYFSQQR95Y/U+vZjk4vua1Ozcj0+1WzZhrRmWX2WhliZlReyxUyK3QHfQPWQ+FWJq+y5DvbOs2kUHINxElSI1XEiRLXjiEsqEdxqTGx7YDoFe+u8CdF6i62Tbx1xQ2Q1sl46yPbGNPivaDFfbH5ef9wUDePiW+u8UfUXXW9rWgShsk1tq4+vrbZ40FaewpYFF/Lz+yjAMVCkjoH9d4NS1+xGp13Cf4nZLbqcm+dJbas4rfEW61oSibrwJKkIFB8vL/MaShsW1fGeGvqNlFc1G/wDl2bT13Wt8eKeSZJVm68W8wUAUHy7J7A6OBu7GMYDGMYDGMYDGMYH/2Q==',
        new Clip(71, 659, 36, 20)
    )
})