/*
    #322 Title is not displaying
    https://github.com/kerssdead/charts/issues/322
 */

import { test } from '@playwright/test'
import Utils from './utils/Utils'
import Settings from './utils/Settings'
import { ChartType } from '../src/static/Enums'
import Clip from './utils/Clip'

test('Plot title should be rendered', async ({ page, browserName }) => {
    await Utils.setup(page, browserName)

    await Settings.enableInitAnimation(false)

    await Settings.enableTitle()
    await Settings.enableLegend()
    await Settings.chartType(ChartType.Plot)

    await Utils.checkScreenshot(
        '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAeADADASIAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAcEBQgCBv/EACwQAAEDBAEEAQIGAwAAAAAAAAECAwQABQYREgcTITFBFXEIFBYiMzhRdrP/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1TRVVk7t4Ysr7mNRYkq6Ap7TUt0ttqHIctqAJHjZ+9KiNnvUuRmczGG8axv6nFiImObnOcO2pXEaPH3v41QOyil+nMrxZrdkU7L4VrjM2m3ol8Ic0LW4521KW3pWinZACSQOW6jRepf5+b04RCjRls5S065I09zMRSY6XeGx7IKtHYH2oGTRUCXerXCmtQ5lyhR5bv8AGw6+lC1/ZJOzU+gKVFl/szkX+vx/+tNeqlnHbWxk0nIWovG7yI6YrsjuKPJpJ2E8d8R5+QN0CRy6JGmZN14RLjsvoRj8Z1KXUBQStEV1SVDfohQBB9ggGuLFAhQJv4fBAix4wfhvvvdltKO46qA3yWrQ8qJ9k+TTs/Stl+p3m4KgoXKvLKI89S1qUl9tKSlKSkniBxUR4A3vzVRj3TLEsfVa1Wq2LaVbH3pMPlLec7K3UBtZHJZ2ClIGjsD2PJJoM94hYbplGK5fdbnjuJ3N+VNlifcrtMUiTDKfBSD2z2ggAEaI8arQvR0zT0xx4XOcxcJSYwQZTDhcQ6kEhCgogE/tCfJHv/Puol/6R4TfrvJuVxs25UpQVJ7Mh1lEgg7BcQhQSo787I2fmvbxY7MSMzGitIZjsoDbbaBpKEgaAA+ABQf/2Q==',
        new Clip(440, 10, 48, 30)
    )
})