/*
    #367 X-axis labels overlap each other
    https://github.com/kerssdead/charts/issues/367
 */

import { test } from '@playwright/test'
import Utils from './utils/Utils'
import Settings from './utils/Settings'
import { ChartType, PlotAxisType, PlotType } from '../src/static/Enums'
import Clip from './utils/Clip'

test('Label should not overlap each other', async ({ page, browserName }) => {
    await Utils.setup(page, browserName)

    await Settings.valuesCount(5)
    await Settings.chartType(ChartType.Plot)
    await Settings.plotType(PlotType.Bar)
    await Settings.xAxisType(PlotAxisType.Text)

    await Utils.checkScreenshot(
        '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAUAYADASIAAhEBAxEB/8QAGgABAQADAQEAAAAAAAAAAAAAAAYCBQcDCP/EACQQAAICAgICAgMBAQAAAAAAAAABAgMEBQYREiETFAcVMRYi/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/APqkAAAAAAAE5zLkduj/AFeJr8GOfttpkvFxMed3wwbUJWSlOfUvGMYwk30m/wCJIy4XyKzkGJnxy8P6Oy12XPBzMeNvywjZGMZJwn0vKLjOEk+k/fTXaNf+QdZsbc7jW80+E9hlaXOlfPEhZGE7qrKbKpqDm1HyXmpJNpPrrsz/AB3qthhV73Y7jGWJmbnZTzvqucZyor+OuqEJSi3Fy8ak302u5ddvoCuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeOZdLHw77q6bMidcJTjTX15WNLtRXbS7f89tHO6vydZgX7unlGoqwbdZq3tpxws1ZbhX34/FZ/zHwt7/AJH2n79+joG1+5+sy/1ToWw+Kf13kRcq/k6fj5JNNx7676afRxjacH3fLc3d2/52ni0s/S5GHnS+aqUdjmTcXXNxqk+4wak/OfU+p9df0Cts/IuTpv2EeZaWOrsx9XZt6o42V9lWUwkozg24Q8bE5wXXtPy9P0zaca5Vs8rkUdJyPS1arOvwnsMZU5f2IzqjOMZxk/CPjOLnDtLtPy9P0yQ3/F+QfkFbS7b6l6Of+fv1dFeRfXa7Mm6UJymnXKSVcXVFJvpvyfpdFDxvF3u55xjch3umnpq8HVzwYUW312ytutshOycfjlJKC+KKTfTfk/S6AvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//Z',
        new Clip(24, 680, 384, 20)
    )
})