/*
    #458 Series should not render outside plot
    https://github.com/kerssdead/charts/issues/458
 */

import { test } from '@playwright/test'
import Utils from './utils/Utils'
import Settings from './utils/Settings'
import { PlotType } from '../src/static/Enums'
import Clip from './utils/Clip'

test('Plot chart should not renders outside plot', async ({ page, browserName }) => {
    await Utils.setup(page, browserName)

    await Settings.valuesCount(1)
    await Settings.pointsCount(20)
    await Settings.seriesWidth(100)
    await Settings.plotType(PlotType.Line)

    await Utils.checkScreenshot(
        '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCADSAAoDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAACAAGB//EACcQAAEDBAIBAgcAAAAAAAAAAAADBQgCNnWzAREEBhIWISIycYOh/8QAFwEBAQEBAAAAAAAAAAAAAAAAAAQCAf/EAB4RAAEFAAMBAQAAAAAAAAAAAAABBAUzgQIDESFh/9oADAMBAAIRAxEAPwDVxVcu0X9rqq+2pPyaOPzxzTVz/KDvwXouc8/Hzhx3z1y2Kc9ftSFCTtV960IY7l70J+Bei7f7hjFNqQoQvRdv9wxim1IUJxpWZjKNUL0Xb/cMYptSFCF6Lt/uGMU2pChDSsRlGqF6Lt/uGMU2pChC9F2/3DGKbUhQhpWIyjVC9F2/3DGKbUhQhei7f7hjFNqQoQ0rEZRqhei7f7hjFNqQoQvRdv8AcMYptSFCGlYjKNUL0Xb/AHDGKbUhQhei7f7hjFNqQoQ0rEZRqhei7f7hjFNqQoQvRdv9wxim1IUIaViMo1QvRdv9wxim1IUIXou3+4YxTakKENKxGUaoXou3+4YxTakKEL0Xb/cMYptSFCGlYjKNUL0Xb/cMYptSFCF6Lt/uGMU2pChDSsRlGqF6Lt/uGMU2pChC9F2/3DGKbUhQhpWIyjVC9F2/3DGKbUhQh5jh6TfWr1N5jq5tfk+H4Kng1I0Vr0+zmqrlROrjqnn6uuqefn10IYNUVOv6ajuK8ehEVCIiKS4//9k=',
        new Clip(883, 261, 10, 210)
    )
})