/*
    #323 Bars overlap each other
    https://github.com/kerssdead/charts/issues/323
 */

import { expect, test } from '@playwright/test'
import { Screenshot } from './utils/Screenshot'
import { BrowserResult } from './utils/BrowserResult'
import { Utils } from './utils/Utils'

test('Bars on plot should has same heights', async ({ page, browserName }) => {
    await Utils.goto(page)

    const valuesCount = page.locator('#values-count'),
        pointsCount = page.locator('#points-count'),
        plotType = page.locator('#plot-type'),
        seriesWidth = page.locator('#series-width'),
        disableInitAnimation = page.locator('#init-animation')

    await disableInitAnimation.setChecked(true)
    await valuesCount.fill('3')
    await plotType.selectOption('3')
    await pointsCount.fill('3')
    await seriesWidth.fill('90')

    await page.click('#chart')

    const frame = await Screenshot.get(page, {
        x: 80,
        y: 240,
        width: 40,
        height: 220
    })

    const result: BrowserResult = {
        chromium: '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCADcACgDASIAAhEBAxEB/8QAGQABAQEBAQEAAAAAAAAAAAAAAAQGBQgH/8QAJRABAAADBQkAAAAAAAAAAAAAAAEE0QIDFVOiBQYWF1RVo6TS/8QAGAEBAAMBAAAAAAAAAAAAAAAAAAIDBQb/xAAcEQEAAQQDAAAAAAAAAAAAAAAAAQIDExRRUpH/2gAMAwEAAhEDEQA/APVIx3MzdHu3rX3wczN0e7etffCGWjmFG1Y7x7DYjHczN0e7etffBzM3R7t6198GWjmDasd49hsRjuZm6PdvWvvgMtHMG1Y7x7DzUAyHFgAAAAAAAAAAAAAAAArw6aytUKmHTWVqhUEgrw6aytUKmHTWVqhUEgrw6aytUKgNCAAAAAAAAAAAAAAAAAAK8OmsrVCph01laoVBIK8OmsrVCph01laoVBIK8OmsrVCoDQgAAAAAAAAAAAAAAAAADt8Kba6Py2KnCm2uj8tiqeKviV+rf6T5LiDt8Kba6Py2KnCm2uj8tipir4k1b/SfJcQdvhTbXR+WxUMVfEmrf6T5L6mA13aAAAAP/9k=',
        firefox: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCADcACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD6porjv+FmeEf+gt/5LTf/ABFH/CzPCP8A0Fv/ACWm/wDiKj2sO6MPrVD+dfejsaK47/hZnhH/AKC3/ktN/wDEUf8ACzPCP/QW/wDJab/4ij2sO6D61Q/nX3o7GiuO/wCFmeEf+gt/5LTf/EUUe1h3QfWqH86+9HzVRRRXkHxYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRVv8As66/55f+PD/Gj+zrr/nl/wCPD/GgCpRVv+zrr/nl/wCPD/Gj+zrr/nl/48P8aAKlFW/7Ouv+eX/jw/xooA6GiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACirf9nXX/ADy/8eH+NH9nXX/PL/x4f40AVKKt/wBnXX/PL/x4f40f2ddf88v/AB4f40AVKKt/2ddf88v/AB4f40UAdDRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRW3/wimtf8+f8A5FT/ABo/4RTWv+fP/wAip/jV+yn2Zv8AVa/8j+5mJRW3/wAIprX/AD5/+RU/xo/4RTWv+fP/AMip/jR7KfZh9Vr/AMj+5mJRW3/wimtf8+f/AJFT/Gij2U+zD6rX/kf3M9Tooor1z7QKKKKACiiigD//2Q==',
        webkit: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSgBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/AABEIAbgAUAMBEQACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APqmgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPHP+F2f9S//AOTv/wBrri+uf3Twf7b/ALn4/wDAD/hdn/Uv/wDk7/8Aa6Prn90P7b/ufj/wA/4XZ/1L/wD5O/8A2uj65/dD+2/7n4/8AP8Ahdn/AFL/AP5O/wD2uj65/dD+2/7n4/8AAD/hdn/Uv/8Ak7/9ro+uf3Q/tv8Aufj/AMAP+F2f9S//AOTv/wBro+uf3Q/tv+5+P/AD/hdn/Uv/APk7/wDa6Prn90P7b/ufj/wA/wCF2f8AUv8A/k7/APa6Prn90P7b/ufj/wAAP+F2f9S//wCTv/2uj65/dD+2/wC5+P8AwA/4XZ/1L/8A5O//AGuj65/dD+2/7n4/8A8criPCCgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA1v7H/wCm/wD45/8AXoAP7H/6b/8Ajn/16AD+x/8Apv8A+Of/AF6AD+x/+m//AI5/9egA/sf/AKb/APjn/wBegA/sf/pv/wCOf/XoAP7H/wCm/wD45/8AXoAP7H/6b/8Ajn/16AD+x/8Apv8A+Of/AF6AD+x/+m//AI5/9egDWoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDW/sf/AKb/APjn/wBegA/sf/pv/wCOf/XoAP7H/wCm/wD45/8AXoAP7H/6b/8Ajn/16AD+x/8Apv8A+Of/AF6AD+x/+m//AI5/9egA/sf/AKb/APjn/wBegA/sf/pv/wCOf/XoAP7H/wCm/wD45/8AXoAP7H/6b/8Ajn/16ANagAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAO3/AOED/wCol/5A/wDsq7fqf9493+xP7/4f8EP+ED/6iX/kD/7Kj6n/AHg/sT+/+H/BD/hA/wDqJf8AkD/7Kj6n/eD+xP7/AOH/AAQ/4QP/AKiX/kD/AOyo+p/3g/sT+/8Ah/wQ/wCED/6iX/kD/wCyo+p/3g/sT+/+H/BD/hA/+ol/5A/+yo+p/wB4P7E/v/h/wQ/4QP8A6iX/AJA/+yo+p/3g/sT+/wDh/wAEP+ED/wCol/5A/wDsqPqf94P7E/v/AIf8EP8AhA/+ol/5A/8AsqPqf94P7E/v/h/wQ/4QP/qJf+QP/sqPqf8AeD+xP7/4f8E7eu094KACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD//Z'
    }

    expect(frame).toBe(result[browserName])
})