/*
    #361 Label overlap cell
    https://github.com/kerssdead/charts/issues/361
 */

import { test } from '@playwright/test'
import Utils from './utils/Utils'
import Settings from './utils/Settings'
import { ChartType } from '../src/static/Enums'
import Clip from './utils/Clip'

test('Tree Map label with spaces should not overflow cell', async ({ page, browserName }) => {
    await Utils.setup(page, browserName)

    await Settings.valuesCount(9)
    await Settings.customLabel('asdsadas   sa  das   d   hhhhh')
    await Settings.chartType(ChartType.TreeMap)
    await Settings.seed(181)

    await Utils.checkScreenshot(
        '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAeANQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAcIBv/EABgQAQADAQAAAAAAAAAAAAAAAAAIRoTD/8QAFwEBAQEBAAAAAAAAAAAAAAAAAAQFBv/EAB8RAQAABAcAAAAAAAAAAAAAAAADQoGxAgQFMzSCwf/aAAwDAQACEQMRAD8A45d5D1/RzQhd5D1/RzZMPax0u5mBx4vW6OAJ0YAAAAAAAAAAAAAAAAAAAA2Mxy2MvyU1GzpE9PQBe2WJV3kPX9HNCF3kPX9HNkw9rHS7mYHHi9bo4AnRgAAAAAAAAAAAAAAAAAAADYzHLYy/JTUbOkT09AF7Zf/Z',
        new Clip(678, 181, 212, 30)
    )
})